BethanysPieShop/BethanysPieShop/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;

namespace BethanysPieShop.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

BethanysPieShop/BethanysPieShop/Controllers/PieController.cs
using System.Collections.Generic;
using System.Linq;
using BethanysPieShop.Models;
using BethanysPieShop.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace BethanysPieShop.Controllers
{
    public class PieController : Controller
    {
        private readonly IPieRepository _pieRepository;
        private readonly ICategoryRepository _categoryRepository;

        public PieController(IPieRepository pieRepository, ICategoryRepository categoryRepository)
        {
            _pieRepository = pieRepository;
            _categoryRepository = categoryRepository;
        }

        // public ViewResult List()
        // {
        //     PiesListViewModel piesListViewModel = new PiesListViewModel();
        //     piesListViewModel.Pies = _pieRepository.AllPies;
        //     piesListViewModel.CurrentCategory = "Cheese Cakes";
        //     
        //     return View(piesListViewModel);
        // }

        public ViewResult List(string category)
        {
            IEnumerable<Pie> pies;
            string currentCategory;

            if (string.IsNullOrEmpty(category))
            {
                pies = _pieRepository.AllPies.OrderBy(p => p.PieId);
                currentCategory = "All pies";
            }
            else
            {
                pies = _pieRepository.AllPies.Where(p => p.Category.CategoryName == category).OrderBy(p => p.PieId);
                /* finds a category, or type Category, in AllCategories IEnumerable. The null-operator '?.' either returns null if
                FirstOrDefault returns the default value of null. CategoryName is the string name property from the Category class */
                currentCategory = _categoryRepository.AllCategories.FirstOrDefault(c => c.CategoryName == category)
                    ?.CategoryName;
            }

            return View(new PiesListViewModel
            {
                Pies = pies,
                CurrentCategory = currentCategory
            });
        }
        
        public IActionResult Details(int id)
        {
            var pie = _pieRepository.GetPieById(id);
            if (pie == null)
            {
                return NotFound();
            }

            return View(pie);
        }
    }
}

BethanysPieShop/BethanysPieShop/Views/Shared/_Carousel.cshtml
@model HomeViewModel

<div class="row carousel-holder">
    <div class="col-md-12">
        <div class="carousel slide" id="carouself-example-generic" data-ride="carousel">
            <ol class="carousel-indicators">
                <li class="active" data-target="#carousel-example-generic" data-slide-to="0"></li>
                <li class="active" data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li class="active" data-target="#carousel-example-generic" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="item active">
                    <img src="/images/carousel1.jpg" alt="" class="slide-image">
                </div>
                <div class="item">
                    <img src="/images/carousel2.jpg" alt="" class="slide-image">
                </div>
                <div class="item">
                    <img src="/images/carousel3.jpg" alt="" class="slide-image">
                </div>
            </div>
            <a href="#carouself-example-generic" data-slide="prev" class="left carousel-control">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a href="#carouself-example-generic" data-slide="next" class="right carousel-control">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>
    </div>
</div>

BethanysPieShop/BethanysPieShop/Views/Shared/_Layout.cshtml
@using BethanysPieShop.Components
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro">
    <link rel="stylesheet" href="/lib/bootstrap/css/bootstrap.css">
    <script src="/lib/jquery/jquery.js"></script>
    <script src="/lib/bootstrap/js/bootstrap.js"></script>
    <link rel="stylesheet" href="~/content/site.css">
    <title>Nathy's Pie Shop</title>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#bs-example">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                @await Component.InvokeAsync(typeof(CategoryMenu))
                <li><a asp-controller="Contact" asp-action="Index">Contact Nathy</a></li>
                @await  Component.InvokeAsync(typeof(ShoppingCartSummary))
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <p class="lead">
                <img src="/images/bethanylogo.png" alt="Nathy's Pie Shop" class="img-responsive">
            </p>
        </div>
        <div>
        </div>
        <div class="col-md-9">
            @RenderBody()
        </div>
    </div>
</div>
</body>
</html>

BethanysPieShop/BethanysPieShop/Views/Shared/_PieCard.cshtml
@model Pie 

<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
        <img src="@Model.ImageThumbnailUrl" alt="">
        <div class="caption">
            <h3 class="pull-right">@Model.Price.ToString("c")</h3>
            <h3>
                <a asp-controller="Pie" asp-action="Details" asp-route-id="@Model.PieId">@Model.Name</a>
            </h3>
            <p>@Model.ShortDesc</p>
        </div>
        <div class="addToCart">
            <p class="button">
                <a asp-controller="ShoppingCart" asp-action="AddToShoppingCart" asp-route-pieId="@Model.PieId" class="btn btn-primary">Add to cart</a>
            </p>
        </div>
    </div>
</div>